services:
  web:
    build: .
    command: bash -c "
        python manage.py migrate &&    
        python manage.py collectstatic --noinput &&
        python manage.py runserver 0.0.0.0:8000
        "
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db_postgres
      - cache_redis
    env_file: ./env/prod.env
  db_postgres:
    image: postgres:16-bullseye
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: ./env/prod.env
  cache_redis:
    image: redis:7.2
    restart: always
    ports:
      - '6379:6379'
    command: bash -c "
      redis-server --save 20 1 --loglevel warning --requirepass $$REDIS_PASSWORD
      "
    volumes: 
      - redis_data:/data
    env_file: ./env/prod.env
volumes:
  postgres_data:
  redis_data:
