services:
  web:
    extends:
      file: compose-base.yaml
      service: web
    env_file: ./env/prod/web.env
  postgres_db:
    extends:
      file: compose-base.yaml
      service: postgres_db
    env_file: ./env/prod/postgres_db.env
volumes:
  postgres_data:
