services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - postgres_db
  postgres_db:
    image: postgres:16-bullseye
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
