services:
  web:
    extends:
      file: compose-prod.yaml
      service: web
    command: bash -c "
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        python manage.py runserver_plus 0.0.0.0:8001 --cert-file cert.crt 
        "
    ports:
      - 8000:8000
      - 8001:8001
  db_postgres:
    extends:
      file: compose-prod.yaml
      service: db_postgres
  cache_redis:
    extends:
      file: compose-prod.yaml
      service: cache_redis
volumes:
  postgres_data:
  redis_data:
